export const API_BASE_URL =
  process.env.EXPO_PUBLIC_API_URL || "https://waste-wise-backend-chi.vercel.app";

export const BARANGAYS = [
  "Airport",
  "Alegria",
  "Alta Vista",
  "Antipolo",
  "Bagong Buhay",
  "Bantigue",
  "Batuan",
  "Bayog",
  "Biliboy",
  "Borok",
  "Cabaon-an",
  "Cabintan",
  "Cabulihan",
  "Cagbuhangin",
  "Camp Downes",
  "Can-adieng",
  "Can-untog",
  "Can-alo",
  "Catmon",
  "Cogon Combado",
  "Concepcion",
  "Curva",
  "Danao",
  "Danhug (Lili-on)",
  "Dayhagan",
  "Dolores",
  "Domonar",
  "Don Carlos B. Rivilla Sr. (Boroc)",
  "Don Felipe Larrazabal",
  "Don Potenciano Larrazabal",
  "Doña Feliza Z. Mejia",
  "Donghol",
  "East Poblacion",
  "Esperanza",
  "Gaas",
  "Green Valley",
  "Guintigui-an",
  "Hibunawon",
  "Hugpa",
  "Ipil",
  "Juaton",
  "Kadaohan",
  "Labrador (Balion)",
  "Lake Danao",
  "Lao",
  "Leondoni",
  "Libertad",
  "Liberty",
  "Licuma",
  "Liloan",
  "Linao",
  "Luna",
  "Mabato",
  "Mabini",
  "Macabug",
  "Magaswi",
  "Mahayag",
  "Mahayahay",
  "Manlilinao",
  "Margen",
  "Mas-in",
  "Matica-a",
  "Milagro",
  "Monterico",
  "Nasunogan",
  "Naungan",
  "Nueva Sociedad",
  "Nueva Vista",
  "North Poblacion",
  "Patag",
  "Punta",
  "Quezon, Jr.",
  "Rufina M. Tan (Rawis)",
  "Sabang Bao",
  "Salvacion",
  "San Antonio",
  "San Isidro",
  "San Jose",
  "San Juan",
  "San Pablo (Simangan)",
  "San Vicente",
  "Santo Niño",
  "South Poblacion",
  "Sumangga",
  "Tambulilid",
  "Tongonan",
  "Valencia",
  "West Poblacion",
  "Barangay 1",
  "Barangay 2",
  "Barangay 3",
  "Barangay 4",
  "Barangay 5",
  "Barangay 6",
  "Barangay 7",
  "Barangay 8",
  "Barangay 9",
  "Barangay 10",
  "Barangay 11",
  "Barangay 12",
  "Barangay 13",
  "Barangay 14",
  "Barangay 15",
  "Barangay 16",
  "Barangay 17",
  "Barangay 18",
  "Barangay 19",
  "Barangay 20",
  "Barangay 21",
  "Barangay 22",
  "Barangay 23",
  "Barangay 24",
  "Barangay 25",
  "Barangay 26",
  "Barangay 27",
  "Barangay 28",
  "Barangay 29",
];

export const USER_ROLES = {
  ADMIN: "administrator",
  ENRO_STAFF: "enro_staff",
  BARANGAY_OFFICIAL: "barangay_official",
  GARBAGE_COLLECTOR: "truck_driver",
  RESIDENT: "resident",
} as const;
